# Generated by Django 4.2 on 2023-04-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
