# Generated by Django 4.2 on 2023-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_userprofile_github_url_userprofile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='steam_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
