# Generated by Django 4.2 on 2023-05-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_userprofile_steam_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
