# Generated by Django 4.2 on 2023-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_userprofile_spotify_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
