# Generated by Django 4.2 on 2023-05-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_userprofile_email_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
